### ISSUE TITLE
Query Params are not passed when redirecting 

### ISSUE THREAD

**Issue by dalejefferson-rnf** [netlify/netlify-dev-plugin#194]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Query params are not passed when redirecting

**- If the current behavior is a bug, please provide the steps to reproduce.**
```toml
[[redirects]]
  from = "/api/*"
  to = "https://engkarv0p2ya.x.pipedream.net/:splat"
  status = 200
```

```sh
curl -v "http://localhost:56064/api/hello?world=true"
```

https://requestbin.com/r/engkarv0p2ya/1MESR2z2YvSdkS11BIm5Yfq9YXs

```http
GET /hello
host: engkarv0p2ya.x.pipedream.net
accept: */*
user-agent: curl/7.54.0
Connection: keep-alive
```
**- What is the expected behavior?**
I expected `GET /hello?world=true`

**- Please mention your node.js, and operating system version.**
node: v8.16.0
os: MacOS 10.14.5
