### ISSUE TITLE
Custom Headers are not passed when redirecting

### ISSUE THREAD

**Issue by dalejefferson-rnf** [netlify/netlify-dev-plugin#195]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Query params are not passed when redirecting

**- If the current behavior is a bug, please provide the steps to reproduce.**
```toml
[[redirects]]
  from = "/api/*"
  to = "https://enbf4i69ldg6q.x.pipedream.net/:splat"
  status = 200
  [redirects.headers]
    X-From = "Netlify"
```

```sh
curl -v http://localhost:57785/api/hello
```

https://requestbin.com/r/enbf4i69ldg6q/1METHwauKX5U1KMtOCQ8qHRk3Ky

```http
GET /hello
host: enbf4i69ldg6q.x.pipedream.net
accept: */*
user-agent: curl/7.54.0
Connection: keep-alive
```
**- What is the expected behavior?**
I expected 

```
GET /hello
host: enbf4i69ldg6q.x.pipedream.net
accept: */*
user-agent: curl/7.54.0
Connection: keep-alive
X-From: Netlify
```

**- Please mention your node.js, and operating system version.**
node: v8.16.0
os: MacOS 10.14.5
